source "https://rubygems.org"

# Specify your gem's dependencies in railsplan.gemspec
gemspec

group :development, :test do
  gem "rspec", "~> 3.12"
  gem "rake", "~> 13.0"
  gem "rubocop", "~> 1.50"
  gem "rubocop-rspec", "~> 2.20"
  gem "simplecov", "~> 0.22"
  gem "webmock", "~> 3.18"
  gem "vcr", "~> 6.1"
end 